### ISSUE TITLE
[ common ] QA 반영

### ISSUE THREAD

**Issue by NYeonK** [TeamPiickle/client#189]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [X] Refactor (리모델링 재개발)
- [x] Fix (내가 해결해주지)
- [X] Feature (제가 해냈습니다)

## 내용

- 기획, 디자인 QA를 반영합니다.

## 체크리스트

- [x] 칸반보드에 있는 에픽 번호를 이슈 이름에 명시
  - EX `[ {페이지명} - {세부명} ] 테스트 이슈명`
- [x] Assignees / Labels / Milestone 선택
### MainPage
- [x] ~Best Piickle 카드를 상하로 움직일 수 있게 만듭니다.~
- [x] Best Piickle Slider 왼쪽 마진 값을 수정합니다.  #194 #201 
- [x] Best Piickle `카드 보기` 버튼의 오타를 제거합니다. #201 
- [x] Best Piickle `카드 보기` 버튼의 width 값을 수정합니다. #194 
- [x] PiickleMe button 영역을 수정합니다. #197 
- [x] Footer height를 수정합니다. #190 
### VotePage
- [x] CTA 버튼을 서비스 화면에 맞게 조절합니다. #192 
- [x] CTA 버튼의 구분선이 스크롤링에 따라 움직이지 않도록 고정시킵니다. #192 
### CategoryPage 
- [x] 상단 배너 텍스트를 수정합니다. #191 
- [x] 상단 배너의 `카드보기>` 버튼 font를 수정합니다. #191 
### CardCollectionPage
- [x] `친밀해요` 카테고리 카드 통신 로직을 수정합니다. #195

**Comment by joohaem** [comment]
기록......야무져요...🧃🧃
