### ISSUE TITLE
[ Common ] QA 반영

### ISSUE THREAD

**Issue by NYeonK** [TeamPiickle/client#269]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [x] Refactor (리모델링 재개발)
- [x] Fix (내가 해결해주지)
- [x] Feature (제가 해냈습니다)

## 내용

- 3번째 스프린트의 기획, 디자인 QA를 반영합니다. (디자인 QA는 전달을 아직 못받았습니다.)

## 체크리스트

- [x] 칸반보드에 있는 에픽 번호를 이슈 이름에 명시
  - EX `[ {페이지명} - {세부명} ] 테스트 이슈명`
- [x] Assignees / Labels / Milestone 선택

### MainPage, PreviewPage
- [ ] 메인페이지에서 메들리 SubText를 제거합니다. (Figma 미반영)

### CardCollectionPage
- [x] `LastCard`의 하단이 안보이는 문제를 해결합니다. #271 
- [x] 상단 헤더의 `카테고리 보기`버튼을 홈 버튼으로 변경합니다. #272 
- [x] 상단 헤더의 `마이 피클 리스트 보기` 버튼을 로그인 한 유저에게만 보이도록 변경합니다. #272 
- [x] 카드 필터에서 랜덤 버튼을 없애고, 여백을 수정합니다. #273
